apiVersion: v1
kind: ConfigMap
metadata:
  name: tald-unia-backend-config
  namespace: tald-unia-system
  labels:
    app: tald-unia
    component: backend
    environment: production
    version: 1.0.0
  annotations:
    configVersion: v1.0.0
    lastUpdated: "2024-01-20"
    description: TALD UNIA Backend Configuration
data:
  # Server Configuration
  NODE_ENV: "production"
  PORT: "3000"
  API_VERSION: "v1"
  MAX_REQUEST_SIZE: "50mb"
  COMPRESSION_ENABLED: "true"
  REQUEST_TIMEOUT: "30000"

  # Database Configuration
  DB_HOST: "postgresql.tald-unia-system.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "tald_unia"
  DB_POOL_MIN: "5"
  DB_POOL_MAX: "20"
  DB_IDLE_TIMEOUT: "10000"

  # Redis Configuration
  REDIS_HOST: "redis.tald-unia-system.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_MAX_RETRIES: "3"
  REDIS_RETRY_INTERVAL: "1000"
  REDIS_KEEP_ALIVE: "true"

  # Audio Processing Configuration
  AUDIO_SAMPLE_RATE: "48000"
  AUDIO_BIT_DEPTH: "24"
  AUDIO_BUFFER_SIZE: "1024"
  AUDIO_CHANNELS: "2"
  AUDIO_FORMAT: "float"
  DSP_THREAD_COUNT: "4"
  SPATIAL_PROCESSING_ENABLED: "true"
  ROOM_CORRECTION_ENABLED: "true"

  # AI Configuration
  AI_MODEL_PATH: "/opt/tald-unia/models"
  AI_INFERENCE_THREADS: "4"
  AI_BATCH_SIZE: "16"
  AI_OPTIMIZATION_LEVEL: "3"
  AI_CACHE_ENABLED: "true"
  AI_FALLBACK_MODE: "cpu"
  MODEL_UPDATE_CHECK_INTERVAL: "3600"

  # Monitoring Configuration
  METRICS_ENABLED: "true"
  METRICS_INTERVAL: "15"
  HEALTH_CHECK_INTERVAL: "30"
  LOG_LEVEL: "info"
  TRACING_ENABLED: "true"