version: 2
updates:
  # Backend Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "backend"
    reviewers:
      - "CODEOWNERS"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
        update-types:
          - "major"
          - "minor"
          - "patch"
      tensorflow:
        patterns:
          - "@tensorflow/*"
        update-types:
          - "minor"
          - "patch"

  # Frontend web dependencies  
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "frontend"
    reviewers:
      - "CODEOWNERS"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      tensorflow:
        patterns:
          - "@tensorflow/*"
        update-types:
          - "minor"
          - "patch"

  # iOS CocoaPods dependencies
  - package-ecosystem: "bundler"
    directory: "/src/ios"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "ios"
    reviewers:
      - "CODEOWNERS"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      cocoapods:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "docker"
    reviewers:
      - "CODEOWNERS"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "ci"
    reviewers:
      - "CODEOWNERS"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"