# PostgreSQL Helm Chart Values
# Chart: bitnami/postgresql v12.5.3
# PostgreSQL Version: 15.4.0

image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 15.4.0-debian-11-r0
  pullPolicy: IfNotPresent

auth:
  enabled: true
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  database: tald_unia
  replicationUsername: repl_user
  replicationPassword: ${REPL_PASSWORD}

primary:
  persistence:
    enabled: true
    storageClass: gp3
    size: 100Gi
    annotations:
      backup.velero.io/backup-volumes: data
  
  resources:
    requests:
      memory: 8Gi
      cpu: "4"
    limits:
      memory: 16Gi
      cpu: "8"
  
  podSecurityContext:
    fsGroup: 1001
    runAsUser: 1001
    runAsNonRoot: true
  
  # PostgreSQL configuration optimized for TALD UNIA workload
  configuration: |
    max_connections = 1000
    shared_buffers = 4GB
    effective_cache_size = 12GB
    maintenance_work_mem = 1GB
    checkpoint_completion_target = 0.9
    wal_buffers = 16MB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    work_mem = 8MB
    min_wal_size = 1GB
    max_wal_size = 4GB
    max_worker_processes = 8
    max_parallel_workers_per_gather = 4
    max_parallel_workers = 8
    max_parallel_maintenance_workers = 4

readReplicas:
  replicaCount: 2
  persistence:
    enabled: true
    storageClass: gp3
    size: 100Gi
  resources:
    requests:
      memory: 8Gi
      cpu: "4"
    limits:
      memory: 16Gi
      cpu: "8"

monitoring:
  enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: "30s"
  grafana:
    enabled: true
    dashboards: true

backup:
  enabled: true
  schedule: "*/15 * * * *"
  retention: "30d"
  storageClass: gp3
  size: 50Gi

networkPolicy:
  enabled: true
  ingressRules:
    - namespaceSelector:
        matchLabels:
          name: tald-unia

# Time-based partitioning configuration
initdbScripts:
  create-partitions.sql: |
    CREATE EXTENSION IF NOT EXISTS timescaledb;
    SELECT create_hypertable('audio_profile', 'created_at', chunk_time_interval => INTERVAL '1 day');
    SELECT create_hypertable('audio_settings', 'created_at', chunk_time_interval => INTERVAL '1 day');

# High Availability configuration
replication:
  enabled: true
  synchronousCommit: "on"
  numSynchronousReplicas: 1
  applicationName: tald-unia

# Performance tuning
postgresql:
  parameters:
    autovacuum: "on"
    autovacuum_vacuum_scale_factor: "0.1"
    autovacuum_analyze_scale_factor: "0.05"
    autovacuum_vacuum_threshold: "50"
    autovacuum_analyze_threshold: "50"
    track_io_timing: "on"
    log_min_duration_statement: "1000"
    statement_timeout: "300000"
    idle_in_transaction_session_timeout: "300000"

# Connection pooling
pgpool:
  enabled: true
  replicas: 2
  maxPool: 4
  numInitChildren: 32
  maxConnections: 1000

# SSL configuration
tls:
  enabled: true
  autoGenerated: true
  certificatesSecret: postgresql-certs
  certFilename: tls.crt
  keyFilename: tls.key
  caFilename: ca.crt

# Archival and WAL configuration
archive:
  enabled: true
  mode: "on"
  command: "test ! -f /archive/%f && cp %p /archive/%f"
  maxStandbyDelay: "30s"
  minRetentionDays: "3"
  maxRetentionDays: "7"