platform :ios, '15.0'
use_frameworks!
inhibit_all_warnings!

def rx_pods
  pod 'RxSwift', '~> 6.5.0'
  pod 'RxCocoa', '~> 6.5.0'
end

def testing_pods
  pod 'RxBlocking', '~> 6.5.0'
  pod 'RxTest', '~> 6.5.0'
end

target 'TALDUnia' do
  rx_pods
  pod 'TensorFlowLiteSwift', '~> 2.13.0'
  pod 'Starscream', '~> 4.0.4'
  pod 'RealmSwift', '~> 10.41.0'
  pod 'SwiftyBeaver', '~> 1.9.5'

  target 'TALDUniaTests' do
    inherit! :search_paths
    testing_pods
  end

  target 'TALDUniaUITests' do
    inherit! :search_paths
    testing_pods
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_BITCODE'] = 'YES'
      config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
      config.build_settings['VALID_ARCHS'] = 'arm64 x86_64'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['ENABLE_TESTABILITY'] = 'YES'
      config.build_settings['MTL_ENABLE_DEBUG_INFO'] = 'NO'
      config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
      config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = config.name == 'Debug' ? 'DEBUG' : ''
      config.build_settings['METAL_ENABLE_DEBUG_INFO'] = 'NO'
      config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '3'
      config.build_settings['LLVM_LTO'] = 'YES'
      config.build_settings['CLANG_OPTIMIZATION_PROFILE_FILE'] = '$(SRCROOT)/OptimizationProfiles/$(PROJECT_NAME).profdata'
    end
  end
end